### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by glebfox** [Anastacia-Galaktionova/1-hw-ui-1#2]
**Requestloan**

`dialogMode` - width="AUTO" и height="AUTO" смогу корректно поджать форму, до нужных размеров. 
`AmountTf`, если указать `datatype="decimal"`, то не придется руками парсить строку в BigDecimal

**ClientBrowse**
По заданию, `requestLoanAction` можно выполнить без выбора клиента из списка, в таком случае поле Client просто не будет предзаполнено. Сейчас, без выбранного клиента, действие игнорируется.

**Comment by Anastacia-Galaktionova** [comment]
Всё поправила
